### ISSUE TITLE
Annihilator Overlord changes

### ISSUE THREAD

**Issue by SergentSilver** [wargame-engine/wzff#19]
In Warhammer, the Necron Destroyer Lord is, I believe, supposed to be a sort of upgrade of the basic Lord and is below the Overlord in terms of the Necron hierarchy system. Here, the equivalent is named Annihilator Overlord and seems to function as an upgrade of the Overlord, but at a reduced points cost. While the naming is not necessarily in error, either the points or the stat line should be changed as it is currently a cheaper, better option to the Overlord with the single exception of not being able to take the Wrist Arrow upgrade.

As a side note that actually is an error, he is listed with the basic 5" movement range rather than the 8" that should be afforded to him by the Annihilator Body.

**Comment by SergentSilver** [comment]
Sorry, I just noticed that the Overlord has Machine Tactics(2) and Tough(1) vs the Annihilator Overlord with just Machine Tactics(1). I don't know exactly what those both do in the Grim Darkness system yet, but it seems likely that the Annihilator Overlord should be just a Annihilator Lord with the movement fix and no other stat line or points cost changes.

**Comment by jaaimino** [comment]
Fixed the movement speed. Also dropped the Save down to annihilator levels
